version: "3"
services:

  client-service:
    #    container_name: client-container
    #    build:
    #      context: ./client
    image: angular/ngcontainer:latest
    volumes:
      - ./client:/usr/local/app/client
    stdin_open: true
    depends_on:
      - nginx
    ports:
      - "4200:4200"
    networks:
      - sena-app

  server-service:
    container_name: server-container
    #    image: bitnami/express:latest
    build:
      context: ./server
    volumes:
      - ./server:/usr/local/app/server
    depends_on:
      - mysql-service
      - nginx
    networks:
      - sena-app
    ports:
      - "8080:8080"

  nginx:
    container_name: ${NGINX_CONTAINER_NAME}
    image: nginx:latest
    ports:
      - "3500:80"
    networks:
      - sena-app

  mysql-service:
    image: mysql:latest
    container_name: ${MYSQL_CONTAINER_NAME}
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - ${MYSQL_PORT}

  phpmyadmin-service:
    image: phpmyadmin:latest
    container_name: ${PHPMYADMIN_CONTAINER_NAME}
    environment:
      - PMA_HOST=${MYSQL_CONTAINER_NAME}
      - PMA_USER=${DB_USER}
    ports:
      - ${PHPMYADMIN_PORT}
networks:
  sena-app:
    driver: bridge