version: "3"
services:

  angular-service:
    image: "angular-image"
    container_name: "angular-container"
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4200:80"

  express-service:
    image: "express-image"
    container_name: "express-container"
    build:
      context: ./server
    volumes:
      - ./server:/app
    ports:
      - "8080:80"

  mysql-service:
    image: mysql:latest
    container_name: mysql-container
    environment:
      - MYSQL_ROOT_PASSWORD=wojtek
      - MYSQL_DATABASE=social-system-for-organizing-rides
      - MYSQL_USER=wojtek
      - MYSQL_PASSWORD=wojtek
    ports:
      - "3306:3306"

  phpmyadmin-service:
    image: phpmyadmin:latest
    container_name: phpmyadmin-container
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql-container
      - PMA_USER=wojtek
      - PMA_PASSWORD=wojtek
    ports:
      - "8888:80"