version: "3.8"
services:
  # Mysql database container
  db:
    image: mysql
    container_name: db_symfony
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - symfony-network

  # phpmyadmin container
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-container
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    networks:
      - symfony-network

  # Angular frontend container
  # angular-service:
  #   container_name: angular-container
  #   build:
  #     context: ./docker/angular
  #     dockerfile: Dockerfile
  #   ports:
  #     - 4200:80 # Map host port 4200 to container port 80
  #   networks:
  #     - symfony-network

  # Symfony Apache project container
  www:
    build: ./docker/php # Update the path to the Symfony app
    container_name: symfony-container
    ports:
      - "8741:80"
    volumes:
      - ./docker/php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    networks:
      - symfony-network

networks:
  symfony-network:

volumes:
  db-data:
